var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/edit-game/[id]/page.js")
R.c("server/chunks/ssr/_1_hp6h0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0z5ob0b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06rgs54._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1as16i8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10vgtr-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_18_d8l1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_profile_edit-game_[id]_page_actions_00c91uv.js")
R.m(81071)
module.exports=R.m(81071).exports
